# Site settings
title: Peter Jacobs
description: Front-end developer passionate about building accessible web apps
baseurl: ""
url: "https://thisispeterj.com"

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Include pages from _pages directory
include: ["_pages"]

# Collections
collections:
  posts:
    output: true

# Default settings for pages
defaults:
  - scope:
      path: "_pages"
    values:
      layout: "default"

# Exclude files from processing
exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - tests/
  - playwright.config.ts
  - .github/
  - README.md
  - scripts.js
  - src/

# Keep your existing files
keep_files:
  - index.html
  - style.css
  - images/
