# Site settings
title: Peter Jacobs
email: your-email@example.com
description: >-
  Front-end developer passionate about building accessible web apps that users love.
baseurl: ""
url: "https://thisispeterj.com"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Blog settings
permalink: /blog/:year/:month/:day/:title/
paginate: 5
paginate_path: "/blog/page:num/"

# Exclude from processing
exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - README.md
