# Site settings
title: Peter Jacobs
description: Front-end developer passionate about building accessible web apps
baseurl: ""
url: "https://thisispeterj.com"

# Build settings
markdown: kramdown
highlighter: rouge

# Jekyll configuration
# plugins:
#   - jekyll-feed
#   - jekyll-sitemap

# Collections
collections:
  posts:
    output: true

# Exclude files from processing
exclude:
  - node_modules/
  - package.json
  - package-lock.json
  - scripts.js
  - src/

# Keep your existing files
keep_files:
  - index.html
  - style.css
  - images/
