name: Playwright Tests

on:
  push:
    branches: [main, develop] # run on pushes to main/develop
  pull_request:
    branches: [main] # run on PRs into main
  schedule:
    - cron: "0 2 * * *" # nightly @ 02:00 UTC

jobs:
  # =========================
  # 1) PR / Push: FAST SMOKE
  #    Build Jekyll and run quick checks
  # =========================
  pr-smoke:
    name: PR/Push Smoke (Built App)
    runs-on: ubuntu-latest
    timeout-minutes: 45
    if: github.event_name == 'pull_request' || github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      # Build local Jekyll site (matches config's local mode)
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true

      - name: Install Jekyll deps
        run: bundle install

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install npm deps
        run: npm ci

      # Cache Playwright browsers by version
      - name: Get Playwright version
        id: pw
        run: |
          VERSION=$(node -p "require('./package.json').devDependencies?.['@playwright/test'] || require('./package.json').dependencies?.['@playwright/test']")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: pw-cache
        with:
          path: ~/.cache/ms-playwright
          key: pw-${{ steps.pw.outputs.version }}

      - name: Install Playwright system deps
        if: steps.pw-cache.outputs.cache-hit != 'true'
        run: npx playwright install-deps

      - name: Install Playwright browsers
        if: steps.pw-cache.outputs.cache-hit != 'true'
        run: npx playwright install

      # Run smoke: all tests on desktop Chromium, and only @mobile-smoke on Mobile Chrome
      - name: Run Chromium (all tests)
        run: npx playwright test --project=chromium
        env:
          CI: true

      - name: Run Mobile Chrome (@mobile-smoke only)
        run: npx playwright test --project="Mobile Chrome" -g "@mobile-smoke"
        env:
          CI: true

      - name: Upload artifacts (HTML report + failure assets)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-pr
          path: |
            playwright-report/
            test-results/
          retention-days: 14

  # =========================
  # 2) Nightly: FULL SUITE
  #    Build Jekyll and run full config projects
  # =========================
  nightly-full:
    name: Nightly Full (Built App)
    runs-on: ubuntu-latest
    timeout-minutes: 90
    if: github.event_name == 'schedule'

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true

      - name: Install Jekyll deps
        run: bundle install

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install npm deps
        run: npm ci

      - name: Get Playwright version
        id: pw
        run: echo "version=$(node -p \"require('./package.json').devDependencies?.['@playwright/test'] || require('./package.json').dependencies?.['@playwright/test']\")" >> $GITHUB_OUTPUT

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: pw-cache
        with:
          path: ~/.cache/ms-playwright
          key: pw-${{ steps.pw.outputs.version }}

      - name: Install Playwright system deps
        if: steps.pw-cache.outputs.cache-hit != 'true'
        run: npx playwright install-deps

      - name: Install Playwright browsers
        if: steps.pw-cache.outputs.cache-hit != 'true'
        run: npx playwright install

      - name: Run Playwright tests (full)
        run: npx playwright test
        env:
          CI: true

      - name: Upload artifacts (HTML report + failure assets)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-nightly
          path: |
            playwright-report/
            test-results/
          retention-days: 30
